name: Deploy CI

on:
  push:
    branches:
      - production
      - staging
      - test
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  deploy:
    uses: "./.github/workflows/deploy-call.yml"
    secrets: inherit
    with:
      is_pr: "${{ github.event_name == 'pull_request' }}"

  checks:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Echo Deployment URL
        run: echo Deployment URL - "${{ needs.deploy.outputs.url }}"
      - name: Ping Site
        run: |
          if curl -Is https://${{ needs.deploy.outputs.url }} | head -n 1 | grep "2\d\d" ; then
            echo "Website is alive!"
          else
            echo "Website returns a non-200 HTTP Code!"
            exit 1
          fi
