name: Deploy CI

on:
  push:
    branches:
      - production
      - staging
      - test
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  deploy:
    uses: "./deploy-call.yml"
    secrets: inherit
    with:
      is_pr: "${{ github.event_name == "pull_request" }}"
