name: Deploy CI

on:
  push:
    branches:
      - production
      - staging
      - test
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:
    inputs:
      is_foo:
        description: "Is this a foo?"
        type: boolean
        required: false
        default: false

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Foo
        run: echo Is Foo - "${{ github.event.inputs.is_foo }}"
      - name: Echo success if foo
        if: github.event.inputs.is_foo == 'true'
        run: echo Success!
      - name: Echo failure if not foo
        if: github.event.inputs.is_foo == ''
        run: echo Failure!

  deploy:
    uses: "./.github/workflows/deploy-call.yml"
    secrets: inherit
    with:
      is_pr: "${{ github.event_name == 'pull_request' }}"

  checks:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Echo Deployment URL
        run: echo Deployment URL - "${{ needs.deploy.outputs.url }}"
      - name: Ping Site
        run: |
          if curl -Is https://${{ needs.deploy.outputs.url }} | head -n 1 | grep -e "2[0-9][0-9]" -e "3[0-9][0-9]" ; then
            echo Website is alive!
          else
            echo Website returned a non-200/300 HTTP Code!
            exit 1
          fi
